"""empty message

Revision ID: 033ffedbe836
Revises: b5a5fc8fae9c
Create Date: 2025-06-16 18:38:23.422833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '033ffedbe836'
down_revision = 'b5a5fc8fae9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_column('quiz_data')
        batch_op.drop_column('video_url')
        batch_op.drop_column('correct_code_result')
        batch_op.drop_column('code_template')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_template', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('correct_code_result', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('video_url', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('quiz_data', mysql.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
